"""
gen_ldpc_matrix.py

Fetches the authoritative FT8 (174,91) LDPC parity-check matrix from
ft8_lib/ft8/constants.c on GitHub, validates it, and writes ldpc_matrix.py
containing _LDPC_CHECKS ready to paste into ft8_decode.py.

ft8_lib layout:
  Nm[M][7]  — M=83 check nodes; each row lists up to 7 variable-node indices
               (1-based, 0 = unused slot).  This is directly the check-node
               adjacency list we need for _LDPC_CHECKS.
  Mn[N][3]  — N=174 variable nodes; each row lists up to 3 check memberships.
"""
import urllib.request, re, sys
import numpy as np

URL = 'https://raw.githubusercontent.com/kgoba/ft8_lib/master/ft8/constants.c'

print(f"Fetching {URL} ...")
data = urllib.request.urlopen(URL, timeout=15).read().decode()
print(f"  Downloaded {len(data)} bytes.")

# ---------------------------------------------------------------------------
# Parse Nm[83][7] — check-node variable lists
# ---------------------------------------------------------------------------
nm_start = data.index('kFTX_LDPC_Nm[FTX_LDPC_M][7]')
nm_end   = data.index('};', nm_start) + 2
nm_block = data[nm_start:nm_end]
nm_rows  = re.findall(r'\{([^}]+)\}', nm_block)
print(f"Nm rows parsed: {len(nm_rows)}  (expected 83)")
assert len(nm_rows) == 83, f"Expected 83 Nm rows, got {len(nm_rows)}"

# Convert to 0-based sorted variable lists, dropping zeros
checks = []
for row_str in nm_rows:
    vals = [int(x) for x in re.findall(r'\d+', row_str)]
    var_indices = sorted(v - 1 for v in vals if v != 0)
    checks.append(tuple(var_indices))

# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------
print("\n=== Validation ===")
all_ok = True
row_lengths = [len(r) for r in checks]
print(f"Row lengths: min={min(row_lengths)} max={max(row_lengths)} "
      f"unique={sorted(set(row_lengths))}")

for i, row in enumerate(checks):
    if len(row) == 0:
        print(f"  ERROR: check {i} is empty"); all_ok = False
    if len(row) != len(set(row)):
        print(f"  ERROR: check {i} has duplicate variable indices"); all_ok = False
    for c in row:
        if not (0 <= c < 174):
            print(f"  ERROR: check {i} index {c} out of range"); all_ok = False

# Build H and check parity submatrix rank
H = np.zeros((83, 174), dtype=np.uint8)
for r, row in enumerate(checks):
    for c in row:
        H[r, c] = 1

def gf2_rank(M):
    A = M.copy().astype(np.uint8)
    nrows, ncols = A.shape
    rank = 0
    for col in range(ncols):
        pivot = next((r for r in range(rank, nrows) if A[r, col]), None)
        if pivot is None:
            continue
        A[[rank, pivot]] = A[[pivot, rank]]
        for row in range(nrows):
            if row != rank and A[row, col]:
                A[row] = (A[row] + A[rank]) % 2
        rank += 1
    return rank

print("Computing GF(2) ranks (may take a few seconds)...")
Hp      = H[:, 91:]
rank_p  = gf2_rank(Hp)
rank_h  = gf2_rank(H)
print(f"  H_parity (83×83) rank over GF(2): {rank_p}  (need 83)")
print(f"  Full H   (83×174) rank over GF(2): {rank_h}  (need 83)")

if rank_p != 83:
    print("  ERROR: parity submatrix is NOT full rank — matrix is wrong!")
    all_ok = False
else:
    print("  Parity submatrix is full rank ✓")

if not all_ok:
    print("\nValidation FAILED — not writing output.")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Write ldpc_matrix.py
# ---------------------------------------------------------------------------
lines = [
    "# ldpc_matrix.py",
    "# Auto-generated by gen_ldpc_matrix.py from ft8_lib/ft8/constants.c",
    "# Source: https://github.com/kgoba/ft8_lib",
    "#",
    "# Paste _LDPC_CHECKS and _FT8_LDPC_FREE_COLS into ft8_decode.py,",
    "# replacing the two placeholder lines.",
    "#",
    f"# Matrix shape: 83 check rows × 174 variable columns",
    f"# Row lengths  : {sorted(set(row_lengths))}",
    f"# H_parity rank: {rank_p}   Full H rank: {rank_h}",
    "",
    "_LDPC_CHECKS: tuple[tuple[int, ...], ...] = (",
]

for row in checks:
    nums = ", ".join(str(c) for c in row)
    lines.append(f"    ({nums},),")

lines += [
    ")",
    "",
    "_FT8_LDPC_FREE_COLS: tuple[int, ...] = tuple(range(91))",
    "",
]

out = "\n".join(lines)
with open("ldpc_matrix.py", "w") as f:
    f.write(out)

print(f"\n=== Written to ldpc_matrix.py ({len(out)} bytes) ===")
print("All checks passed ✓")
